### ISSUE TITLE
Persistent homework highscore data stored in mongodb

### ISSUE THREAD

**Issue by kennarddh** [DogeMultiverse/watermelonbot#33]
https://github.com/alexpvpmindustry/watermelonbot/blob/master/mastermelon/homework_game.py#L72-L72

**Comment by alexpvpmindustry** [comment]
It's called beta for a reason

**Comment by kennarddh** [comment]
Lol ok i guess....

**Comment by kennarddh** [comment]
Beta for 1 year....

**Comment by alexpvpmindustry** [comment]
u wan to code?
~~mindustry v7 was alpha for 1 year~~

**Comment by leblancogato** [comment]
god damn it I told you I am very busy preparing for the High school entrance test, I quit for now, I will come back when I am free

**Comment by kennarddh** [comment]
Maybe i can try but i havent used python in 1 or 2 years. Ill try it.

**Comment by alexpvpmindustry** [comment]
all the best 👍

**Comment by kennarddh** [comment]
Do you have any style guide?

**Comment by kennarddh** [comment]
Do you know why this throw error. I just forked, cloned and run this repo and it throw this error when I run it.

```
D:\___\watermelonbot\venv\Scripts\python.exe D:\___\watermelonbot\main.py 
Hi, PyCharm
Traceback (most recent call last):
  File "D:\___\watermelonbot\main.py", line 17, in <module>
    melon.runbot()
  File "D:\___\watermelonbot\mastermelon\melon.py", line 960, in runbot
    bot.add_cog(giveaway_bot.Giveaway(bot))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\___\watermelonbot\mastermelon\giveaway_bot.py", line 63, in __init__
    self.bot.loop.create_task(self.giveaway_background_task())
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\___\watermelonbot\venv\Lib\site-packages\discord\client.py", line 140, in __getattr__
    raise AttributeError(msg)
AttributeError: loop attribute cannot be accessed in non-async contexts. Consider using either an asynchronous main function and passing it to asyncio.run or using asynchronous initialisation hooks such as Client.setup_hook

Process finished with exit code 1
```

**Comment by alexpvpmindustry** [comment]
It's because of version of discord.py.
Watermelonbot is not compatible with discord.py==2.
We using version 1.7.
See the requirements.txt

**Comment by alexpvpmindustry** [comment]
@kennarddh

**Comment by kennarddh** [comment]
Ok i try to run this now `pip install -r requirements.txt`

But Pillow throw this

```
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [186 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-cpython-311\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext
     
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
      Traceback (most recent call last):
        File "C:\Users___\AppData\Local\Temp\pip-install-ubo30vuw\pillow_3100c0640a4941dbaf9dcc090714e6ba\setup.py", line 865, in <module>
          setup(
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "D:\___\watermelonbot\venv\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "D:\___\watermelonbot\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users___\AppData\Local\Temp\pip-install-ubo30vuw\pillow_3100c0640a4941dbaf9dcc090714e6ba\setup.py", line 702, in build_extensions     
          raise RequiredDependencyException(f)
      RequiredDependencyException: zlib
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users___\AppData\Local\Temp\pip-install-ubo30vuw\pillow_3100c0640a4941dbaf9dcc090714e6ba\setup.py", line 922, in <module>
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects
```

**Comment by alexpvpmindustry** [comment]
Can u try pip install requirements.txt in a new environment?
I think something is messing with pillow.

**Comment by kennarddh** [comment]
> Can u try pip install requirements.txt in a new environment? I think something is messing with pillow.

ok

**Comment by kennarddh** [comment]
so i just need to remove the venv dir?

**Comment by alexpvpmindustry** [comment]
I'm not sure. But sure. Also have u set up a mongodb account?

**Comment by kennarddh** [comment]
i use the local community version

**Comment by kennarddh** [comment]
i created new venv and run `pip install -r requirements.txt` but still same pillow error

But if i run `pip install Pillow` its working and it installed Pillow `10.0.1`

**Comment by alexpvpmindustry** [comment]
requirements.txt and stable-req.txt?
not too sure. u can try either, but I think requirements.txt is used, I might be wrong.

pillow is not too important, because its only used to generate the certificate when people first join the discord.

for fixing the w?homework, u don't need pillow.....

**Comment by kennarddh** [comment]
Yes but it won't install the rest of the `requirements.txt` when pillow throw the error

Ok i just upgraded the pillow just for my local env so i use the latest version `10.0.1`

Also idk why when i install the `requirements.txt` it will install `discord==1.7.3` but it will also install `discord.py==2.1.3` so i need to manually install `discord.py==1.7.3` after i install the `requirements.txt`

The packages problem is solved for now...

I think i can just ignore the channel specific update like this `await git_update_channel.send(f"melon bot started at {get_date_str()}")` because i dont have the channel in my discord server

**Comment by alexpvpmindustry** [comment]
Correct.
U can set it to be your discord's channel ID if u want.
It is a long number

**Comment by kennarddh** [comment]
Do i need to use `w?` prefix because the db is only get for `w?` prefix?

**Comment by alexpvpmindustry** [comment]
U can define your own prefix in the config.alex file... U can use any
prefix for ur own server.
